---
title: "STAT-5361 Homework#8"
author: "Simiao Gao"
output: pdf_document
---

## Exercises 5.3.3

### (1)
$$\begin{aligned}
\mathrm dr(t) = [g(t)+h(t)r(t)] \mathrm dt + \sigma(t) \mathrm dW(t) \\
\text{Hence, } g(t) =\alpha b, \, h(t) =-\alpha,\,\sigma(t)=\sigma 
\end{aligned}$$
$$\begin{aligned}
\mathrm d (e^{\alpha t} r(t)) &= e^{\alpha t} \alpha b \,\mathrm dt + e^{\alpha t} \sigma \,\mathrm dW(t) \\
e^{\alpha t} r(t) &= r(0) + \alpha b \int_0^t e^{\alpha s} \,\mathrm ds + \sigma \int_0^t e^{\alpha s} \,\mathrm d W(s) \;\cdots (1)\\
e^{\alpha (t+\Delta)} r(t+\Delta) &= r(0) + \alpha b \int_0^{t+\Delta} e^{\alpha s} \,\mathrm ds + \sigma \int_0^{t+\Delta} e^{\alpha s} \,\mathrm d W(s) \;\cdots (2) 
\end{aligned}$$

$$(2) - (1) \, \implies r(t+\Delta) = e^{-\alpha \Delta} r(t) + b(1-e^{-\alpha}) + \sigma \int_t^{t+\Delta} e^{\alpha s} \,\mathrm d W(s)$$

$$\begin{aligned}
\sigma_r^2(t,t+\Delta) &= \int_t^{t+\Delta} e^{2\alpha (s-t-\Delta)} \,\mathrm ds       \\
&=\frac{\sigma^2}{2\alpha} (1-e^{-2\alpha}) 
\end{aligned}$$

Therefore,
$$r(t+\Delta) = e^{-\alpha \Delta} r(t) + b(1-e^{-\alpha}) + \frac{\sigma}{\sqrt{2\alpha}} \sqrt{1-e^{-2\alpha \Delta}}Z$$



### (2)

```{r message=FALSE, warning=FALSE}
rand.walk <- function(alpha, sigma, b, r0, time, delta) {
  r <- vector()
  t <- 0
  int <- 1
  while (t <= time) {
    z <- rnorm(1)
    r1 <- exp(-alpha * delta) *r0 + 
      b * (1 - exp(-alpha * delta)) + 
      sigma * sqrt(1 - exp(-2 * alpha * delta)) * z / sqrt(2 * alpha)
    r[int] <- r1
    r0 <- r1
    int <- int + 1
    t <- t + delta
  }
  return(r)
}
```

```{r message=FALSE, warning=FALSE}
set.seed(2020)
alpha <- c(0.1, 1, 5)
sigma <- c(0.1, 0.2, 0.5)
b <- c(-5, 5)
r0 <- 1
time <- 500
delta <- 1/500
mat <- matrix(rep(NA, 3 * 250000), 3, 250000)
```

```{r message=FALSE, warning=FALSE}
par(mar=c(5.1, 4.1, 4.1, 6.1), xpd=TRUE)
for (i in 1:3) {
  mat[i, ] <- rand.walk(0.1, sigma[i], -5, r0, time, delta)
}
plot(ts(mat[1, ], frequency=500),type='l', ylab = "", 
     main = "b = -5, alpha = 0.1", col = "blue", ylim = c(-9, 2))
lines(ts(mat[2, ], frequency=500), type='l', col="red") 
lines(ts(mat[3, ], frequency=500), type='l', col="darkolivegreen1")
legend("topright", inset=c(-0.2,0), legend=c('0.1', '0.2', '0.5'),
       lty=c(1,1,1), col=c("blue", "red", "darkolivegreen1"), title="sigma")

for (i in 1:3) {
  mat[i, ] <- rand.walk(1, sigma[i], -5, r0, time, delta)
}
plot(ts(mat[1, ], frequency=500),type='l', ylab = "", 
     main = "b = -5, alpha = 1", col = "blue", ylim = c(-9, 2))
lines(ts(mat[2, ], frequency=500), type='l', col="red") 
lines(ts(mat[3, ], frequency=500), type='l', col="darkolivegreen1")
legend("topright",  inset=c(-0.2,0), legend=c('0.1', '0.2', '0.5'),
       lty=c(1,1,1), col=c("blue", "red", "darkolivegreen1"), title="sigma")

for (i in 1:3) {
  mat[i, ] <- rand.walk(5, sigma[i], -5, r0, time, delta)
}
plot(ts(mat[1, ], frequency=500),type='l', ylab = "", 
     main = "b = -5, alpha = 5", col = "blue", ylim = c(-9, 2))
lines(ts(mat[2, ], frequency=500), type='l', col="red") 
lines(ts(mat[3, ], frequency=500), type='l', col="darkolivegreen1")
legend("topright", inset=c(-0.2,0), legend=c('0.1', '0.2', '0.5'),
       lty=c(1,1,1), col=c("blue", "red", "darkolivegreen1"), title="sigma")

for (i in 1:3) {
  mat[i, ] <- rand.walk(0.1, sigma[i], 5, r0, time, delta)
}
plot(ts(mat[1, ], frequency=500),type='l', ylab = "", 
     main = "b = 5, alpha = 0.1", col = "blue", ylim = c(0, 9))
lines(ts(mat[2, ], frequency=500), type='l', col="red") 
lines(ts(mat[3, ], frequency=500), type='l', col="darkolivegreen1")
legend("topright", inset=c(-0.2,0), legend=c('0.1', '0.2', '0.5'),
       lty=c(1,1,1), col=c("blue", "red", "darkolivegreen1"), title="sigma")

for (i in 1:3) {
  mat[i, ] <- rand.walk(1, sigma[i], 5, r0, time, delta)
}
plot(ts(mat[1, ], frequency=500),type='l', ylab = "", 
     main = "b = 5, alpha = 1", col = "blue", ylim = c(0, 9))
lines(ts(mat[2, ], frequency=500), type='l', col="red") 
lines(ts(mat[3, ], frequency=500), type='l', col="darkolivegreen1")
legend("topright", inset=c(-0.2,0), legend=c('0.1', '0.2', '0.5'),
       lty=c(1,1,1), col=c("blue", "red", "darkolivegreen1"), title="sigma")

for (i in 1:3) {
  mat[i, ] <- rand.walk(5, sigma[i], 5, r0, time, delta)
}
plot(ts(mat[1, ], frequency=500),type='l', ylab = "", 
     main = "b = 5, alpha = 5", col = "blue", ylim = c(0, 9))
lines(ts(mat[2, ], frequency=500), type='l', col="red") 
lines(ts(mat[3, ], frequency=500), type='l', col="darkolivegreen1")
legend("topright", inset=c(-0.2,0), legend=c('0.1', '0.2', '0.5'),
       lty=c(1,1,1), col=c("blue", "red", "darkolivegreen1"), title="sigma")
```

When $\sigma$ gets larger, the fluctuation is severer. When $\alpha$ gets larger, the range of fluctuation becomes narrower.

### (3)



```{r message=FALSE, warning=FALSE}
euler <- function(alpha, sigma, b, r0, delta) { 
  n <- 1/delta
  r <- vector()
  int <- 1
  for (i in 1:n) {
    r1 <- r0 + alpha * (b - r0) * delta +
      sigma * delta * rnorm(1) 
    r[int] <- r1
    r0 <- r1
    int <- int + 1
    }
  return(r) 
}

alpha <- 0.1
sigma <- 0.1
b <- 5
delta <- c(1, 0.5, 0.1, 0.01)
r0 <- 1
mu <- exp(-sigma * delta[1]) * r0 + b * (1 - exp(-alpha * delta[1])) 
sig <- sigma * sqrt((1 - exp(-2 * alpha * delta[1])) / (2 * alpha))

true <- function (x) {
  exp(-((x - mu)^2) /(2 * sig^2)) / sqrt(2 * pi * sig^2)
}

sim <- matrix(rep(NA, 4*100), 4, 1000)
for (i in 1:4) {
  for (j in 1:1000) {
    sim[i,j] <- euler(alpha, sigma, b, r0, delta[i])[1/delta[i]]
  }
}

hist(sim[1,], freq = F, xlab = '', main = 'delta = 1', ylim = c(0,10)) 
lines(density(sim[1,]), col = "blue", lwd = 1)
curve(true, add = T, col = "red")
legend('topright', legend = c("simulated","true"),
lty = c(1, 1), lwd = c(1, 1), col = c("blue", "red"))

hist(sim[2,], freq = F, xlab = '', main = 'delta = 0.5', ylim = c(0,10)) 
lines(density(sim[2,]), col = "blue", lwd = 1)
curve(true, add = T, col = "red")
legend('topright', legend = c("simulated","true"),
lty = c(1, 1), lwd = c(1, 1), col = c("blue", "red"))

hist(sim[3,], freq = F, xlab = '', main = 'delta = 0.1', ylim = c(0,15)) 
lines(density(sim[3,]), col = "blue", lwd = 1)
curve(true, add = T, col = "red")
legend('topright', legend = c("simulated","true"),
lty = c(1, 1), lwd = c(1, 1), col = c("blue", "red"))

hist(sim[4,], freq = F, xlab = '', main = 'delta = 0.01', ylim = c(0,50)) 
lines(density(sim[4,]), col = "blue", lwd = 1)
curve(true, add = T, col = "red")
legend('topright', legend = c("simulated","true"),
lty = c(1, 1), lwd = c(1, 1), col = c("blue", "red"))

```

## Exercises 5.3.4

### (1)
$$N(5) \sim Poisson(Z)$$
$$\begin{aligned}
Z &= \int_0^5 \lambda(t) \mathrm dt \\
&= \int_0^5 [\sqrt{t}+e^{-t} \sin(2\pi t)] \mathrm dt \\
\int_0^5 e^{-t} \sin(2\pi t) \mathrm dt &=\int_0^5 -\sin(2\pi t) \mathrm d(e^{-t}) \\
&= [-e^{-t}\sin(2\pi t)]_0^5 - \int_0^5 -e^{-t} \mathrm d(\sin(2\pi t)) \\
&= [-e^{-t}\sin(2\pi t)]_0^5 - \int_0^5 -2\pi e^{-t} \cos(2\pi t) \mathrm dt \\
\int_0^5 -2\pi e^{-t} \cos(2\pi t) \mathrm dt &= 2\pi e^{-t} \cos(2\pi t) + 4\pi^2 \int_0^5 e^{-t} \sin(2\pi t) \mathrm dt \\
\implies \int_0^5 e^{-t} \sin(2\pi t) \mathrm dt &= [\frac{-e^{-t} \sin(2\pi t)-2\pi e^{-t}\cos(2\pi t)}{4\pi^2+1}]_0^5 \\
\int_0^5 \sqrt{t} \mathrm dt &= [\frac{2t^{3/2}}{3}]_0^5 \\
\implies Z&= \frac{2e^{-5}(4 \cdot 5^{3/2}e^5 \pi^2 + (3e^5-3)\pi + 5^{3/2}e^5)}{3(4\pi^2+1)}
\end{aligned}$$

### (2)
```{r message=FALSE, warning=FALSE}
t.max <- 5
f <- function(x) {
  return(sqrt(x) + exp(-x) * sin(2 * pi * x)) 
}

sim <- function(n) {
  out <- vector()
  for (i in 1:n) {
    s <- rpois(1, f(t.max) * t.max)
    tt <- runif(s, 0, t.max)
    u <- runif(s)
    accept <- vector()
    for (j in 1:s) {
      accept[j] <- u[j] < f(tt[j]) / f(t.max)
    }
    tt1 <- sort(tt[accept])
    out <- c(out, tt1)
  }
  return(out)
}

```

### (3)

```{r message=FALSE, warning=FALSE}
set.seed(2020)
s <- sim(1000)
f.true <- function(x) {
  z <- 2 * exp(-5) * (4 * 5^1.5 * exp(5) * pi^2 +
                        (3 * exp(5) - 3) * pi + 5^1.5 * exp(5)) / (3 * (4 * pi^2 + 1))
  return(f(x) / z)
}

hist(s, xlab = 'time', main = '', freq = FALSE)
lines(density(s), xlim = c(0,5), col = "blue", lwd = 2)
curve(f.true, 0, 5, add = T, col = "red", lwd = 2)
legend('topleft', legend = c("kernel density","true density"),
       lty = c(1,1), lwd = c(1,1), col=c('blue','red'), cex = 0.9)
```














